-- MySQL Script generated by MySQL Workbench
-- Fri Mar 27 22:26:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema staycare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema staycare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `staycare` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `staycare` ;

-- -----------------------------------------------------
-- Table `staycare`.`_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`_migrations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(255) NOT NULL,
  `applied_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_migrations_filename` (`filename` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Registro de migraciones aplicadas';


-- -----------------------------------------------------
-- Table `staycare`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_roles_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `staycare`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `language` ENUM('en', 'es') NOT NULL DEFAULT 'en',
  `role_id` INT UNSIGNED NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `refresh_token` VARCHAR(512) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_users_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uq_users_phone` (`phone` ASC) VISIBLE,
  INDEX `idx_users_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `staycare`.`roles` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `staycare`.`client_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`client_profiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `contact_person` VARCHAR(150) NOT NULL,
  `vat_number` VARCHAR(50) NOT NULL,
  `billing_address` TEXT NOT NULL,
  `credits_terms_days` SMALLINT UNSIGNED NOT NULL DEFAULT '30',
  `pricing_tier` ENUM('standard', 'premium', 'enterprise') NOT NULL DEFAULT 'standard',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_client_profiles_user` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_client_profiles_vat` (`vat_number` ASC) VISIBLE,
  CONSTRAINT `fk_client_profiles_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `staycare`.`invitations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`invitations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL COMMENT 'UUID hex de 64 chars',
  `email` VARCHAR(150) NOT NULL,
  `role` ENUM('admin', 'staff', 'driver') NOT NULL COMMENT 'Nunca client — ese rol se crea via /auth/register',
  `created_by` INT UNSIGNED NOT NULL COMMENT 'Admin que generó la invitación',
  `used` TINYINT(1) NOT NULL DEFAULT '0',
  `used_at` DATETIME NULL DEFAULT NULL,
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_invitations_token` (`token` ASC) VISIBLE,
  INDEX `idx_invitations_email` (`email` ASC) VISIBLE,
  INDEX `idx_invitations_expires` (`expires_at` ASC) VISIBLE,
  INDEX `fk_invitations_creator` (`created_by` ASC) VISIBLE,
  CONSTRAINT `fk_invitations_creator`
    FOREIGN KEY (`created_by`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tokens de invitación de un solo uso para alta de personal';


-- -----------------------------------------------------
-- Table `staycare`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`invoices` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_number` VARCHAR(30) NOT NULL COMMENT 'Formato INV-AAMM-XXXX',
  `client_id` INT UNSIGNED NOT NULL,
  `issue_date` DATE NOT NULL,
  `due_date` DATE NOT NULL COMMENT 'issue_date + clients.credits_terms_days',
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `vat_percentage` DECIMAL(5,2) NOT NULL DEFAULT '18.00',
  `vat_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `status` ENUM('pending', 'paid', 'overdue') NOT NULL DEFAULT 'pending',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_invoices_number` (`invoice_number` ASC) VISIBLE,
  INDEX `idx_invoices_client` (`client_id` ASC) VISIBLE,
  INDEX `idx_invoices_status` (`status` ASC) VISIBLE,
  INDEX `idx_invoices_due_date` (`due_date` ASC) VISIBLE,
  INDEX `idx_invoices_client_status` (`client_id` ASC, `status` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Facturas emitidas a clientes';


-- -----------------------------------------------------
-- Table `staycare`.`invoice_line_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`invoice_line_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` INT UNSIGNED NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `quantity` SMALLINT UNSIGNED NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_inv_lines_invoice` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_lines_invoice`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `staycare`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Líneas de detalle de cada factura';


-- -----------------------------------------------------
-- Table `staycare`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`properties` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `property_name` VARCHAR(200) NOT NULL,
  `address` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  `access_notes` TEXT NULL DEFAULT NULL,
  `lat` DECIMAL(10,7) NULL DEFAULT NULL,
  `lng` DECIMAL(10,7) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_properties_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_properties_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `staycare`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_number` VARCHAR(30) NOT NULL COMMENT 'Formato ORD-AAMM-XXXX generado en la aplicación',
  `client_id` INT UNSIGNED NOT NULL,
  `property_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Sede de recogida/entrega',
  `driver_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Conductor asignado. NULL si Pending',
  `service_type` ENUM('standard', 'express') NOT NULL,
  `pickup_date` DATE NOT NULL,
  `pickup_window_start` DATETIME NOT NULL,
  `pickup_window_end` DATETIME NOT NULL,
  `estimated_bags` SMALLINT UNSIGNED NULL DEFAULT NULL COMMENT 'Bolsas estimadas por el cliente',
  `actual_bags` SMALLINT UNSIGNED NULL DEFAULT NULL COMMENT 'Bolsas reales contadas en recogida',
  `staff_confirmed_bags` SMALLINT UNSIGNED NULL DEFAULT NULL COMMENT 'Bolsas reales recibidas en planta',
  `special_notes` TEXT NULL DEFAULT NULL,
  `status` ENUM('Pending', 'Assigned', 'Transit', 'Arrived', 'Washing', 'Drying', 'Ironing', 'QualityCheck', 'ReadyToDeliver', 'Collected', 'Delivered', 'facturado', 'Completed') NOT NULL DEFAULT 'Pending',
  `subtotal` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `vat_percentage` DECIMAL(5,2) NOT NULL DEFAULT '18.00',
  `vat_amount` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `total` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_orders_number` (`order_number` ASC) VISIBLE,
  INDEX `idx_orders_client` (`client_id` ASC) VISIBLE,
  INDEX `idx_orders_driver` (`driver_id` ASC) VISIBLE,
  INDEX `idx_orders_property` (`property_id` ASC) VISIBLE,
  INDEX `idx_orders_status` (`status` ASC) VISIBLE,
  INDEX `idx_orders_pickup_date` (`pickup_date` ASC) VISIBLE,
  INDEX `idx_orders_status_date` (`status` ASC, `pickup_date` ASC) VISIBLE,
  CONSTRAINT `fk_orders_client_user`
    FOREIGN KEY (`client_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_property`
    FOREIGN KEY (`property_id`)
    REFERENCES `staycare`.`properties` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Pedidos de lavandería — entidad central del sistema';


-- -----------------------------------------------------
-- Table `staycare`.`invoice_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`invoice_orders` (
  `invoice_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`invoice_id`, `order_id`),
  INDEX `idx_invoice_orders_order` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_orders_invoice`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `staycare`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inv_orders_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Pivote N:M entre facturas y pedidos';


-- -----------------------------------------------------
-- Table `staycare`.`invoice_payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`invoice_payments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `invoice_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `method` ENUM('cash', 'bank_transfer', 'card') NOT NULL,
  `transaction_reference` VARCHAR(200) NOT NULL,
  `paid_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_inv_payments_invoice` (`invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_inv_payments_invoice`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `staycare`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Pagos registrados por factura — soporta parciales';


-- -----------------------------------------------------
-- Table `staycare`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `base_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00' COMMENT 'Precio de referencia. El pedido puede usar un precio distinto',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_items_code` (`item_code` ASC) VISIBLE,
  INDEX `idx_items_is_active` (`is_active` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Catálogo de servicios y productos de lavandería';


-- -----------------------------------------------------
-- Table `staycare`.`machines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`machines` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `type` ENUM('washer', 'dryer', 'iron') NOT NULL,
  `capacity` DECIMAL(6,2) NOT NULL COMMENT 'Capacidad en kg',
  `status` ENUM('available', 'running', 'maintenance') NOT NULL DEFAULT 'available',
  `current_order_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'NULL si status = available',
  `started_at` DATETIME NULL DEFAULT NULL COMMENT 'Inicio del ciclo actual — para calcular tiempo en uso',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_machines_name` (`name` ASC) VISIBLE,
  INDEX `idx_machines_status` (`status` ASC) VISIBLE,
  INDEX `idx_machines_type` (`type` ASC) VISIBLE,
  INDEX `fk_machines_order` (`current_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_machines_order`
    FOREIGN KEY (`current_order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Maquinaria de planta: lavadoras, secadoras, planchas';


-- -----------------------------------------------------
-- Table `staycare`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`order_items` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `item_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Referencia al catálogo. NULL si el ítem fue eliminado',
  `item_code_snapshot` VARCHAR(20) NOT NULL COMMENT 'Código copiado — inmutable',
  `name_snapshot` VARCHAR(200) NOT NULL COMMENT 'Nombre copiado — inmutable',
  `quantity` SMALLINT UNSIGNED NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL COMMENT 'Precio en el momento del pedido',
  `total_price` DECIMAL(10,2) NOT NULL COMMENT 'quantity × unit_price',
  `qty_good` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `qty_bad` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `qty_stained` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idx_order_items_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_items_item` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `staycare`.`items` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_items_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Ítems de cada pedido — snapshot inmutable de precio y nombre';


-- -----------------------------------------------------
-- Table `staycare`.`order_photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`order_photos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `photo_url` VARCHAR(500) NOT NULL COMMENT 'URL externa — S3 o Cloudinary',
  `type` ENUM('before', 'after') NOT NULL,
  `uploaded_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_order_photos_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_photos_type` (`order_id` ASC, `type` ASC) VISIBLE,
  CONSTRAINT `fk_order_photos_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Fotos de evidencia de recogida (before) y entrega (after)';


-- -----------------------------------------------------
-- Table `staycare`.`order_status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`order_status_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `changed_by_user_id` INT UNSIGNED NULL DEFAULT NULL COMMENT 'NULL cuando is_system = TRUE',
  `is_system` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '1 si lo cambió autoAssign u otro automatismo',
  `status` VARCHAR(30) NOT NULL,
  `note` TEXT NULL DEFAULT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_order_history_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_history_date` (`order_id` ASC, `changed_at` ASC) VISIBLE,
  INDEX `fk_order_history_user` (`changed_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_history_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_history_user`
    FOREIGN KEY (`changed_by_user_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Auditoría completa de transiciones de estado por pedido';


-- -----------------------------------------------------
-- Table `staycare`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`password_resets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `used` TINYINT(1) NOT NULL DEFAULT '0',
  `expires_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_password_resets_token` (`token` ASC) VISIBLE,
  INDEX `idx_password_resets_email` (`email` ASC) VISIBLE,
  INDEX `idx_password_resets_exp` (`expires_at` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Tokens de recuperación de contraseña';


-- -----------------------------------------------------
-- Table `staycare`.`routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`routes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `route_date` DATE NOT NULL,
  `driver_id` INT UNSIGNED NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  `status` ENUM('planned', 'in_progress', 'completed') NOT NULL DEFAULT 'planned',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_routes_driver` (`driver_id` ASC) VISIBLE,
  INDEX `idx_routes_date` (`route_date` ASC) VISIBLE,
  INDEX `idx_routes_status` (`status` ASC) VISIBLE,
  INDEX `idx_routes_date_driver` (`route_date` ASC, `driver_id` ASC) VISIBLE,
  CONSTRAINT `fk_routes_driver`
    FOREIGN KEY (`driver_id`)
    REFERENCES `staycare`.`users` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Rutas de reparto diarias por conductor y zona';


-- -----------------------------------------------------
-- Table `staycare`.`route_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staycare`.`route_orders` (
  `route_id` INT UNSIGNED NOT NULL,
  `order_id` INT UNSIGNED NOT NULL,
  `position` SMALLINT UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Orden de parada dentro de la ruta',
  PRIMARY KEY (`route_id`, `order_id`),
  INDEX `idx_route_orders_order` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_orders_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `staycare`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_route_orders_route`
    FOREIGN KEY (`route_id`)
    REFERENCES `staycare`.`routes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Pivote N:M entre rutas y pedidos con orden de parada';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Seed Data: Roles
-- -----------------------------------------------------
INSERT INTO `staycare`.`roles` (`id`, `name`) VALUES 
(1, 'admin'),
(2, 'staff'),
(3, 'driver'),
(4, 'client'),
(5, 'operator')
ON DUPLICATE KEY UPDATE name=name;

-- -----------------------------------------------------
-- Seed Data: Users (Password: password123)
-- -----------------------------------------------------
INSERT INTO `staycare`.`users` (`id`, `name`, `email`, `password_hash`, `role_id`) VALUES
(1, 'System Admin', 'admin@staycare.com', '$2b$10$ASu3vm3RtjKb1iTyms64hOdeTET8BT5/OMwgjOyZVZxGo.1WJh94m', 1),
(2, 'Plant Staff', 'staff@staycare.com', '$2b$10$ASu3vm3RtjKb1iTyms64hOdeTET8BT5/OMwgjOyZVZxGo.1WJh94m', 2),
(3, 'Main Driver', 'driver@staycare.com', '$2b$10$ASu3vm3RtjKb1iTyms64hOdeTET8BT5/OMwgjOyZVZxGo.1WJh94m', 3),
(4, 'Test Client', 'client@staycare.com', '$2b$10$ASu3vm3RtjKb1iTyms64hOdeTET8BT5/OMwgjOyZVZxGo.1WJh94m', 4)
ON DUPLICATE KEY UPDATE email=email;


-- -----------------------------------------------------
-- Seed Data: Client Profile (Required for client user)
-- -----------------------------------------------------
INSERT INTO `staycare`.`client_profiles` (`id`, `user_id`, `contact_person`, `vat_number`, `billing_address`) VALUES
(1, 4, 'Test Client Contact', 'VAT12345678', '123 Business St, City')
ON DUPLICATE KEY UPDATE vat_number=vat_number;
